//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string TOUCH_EVENT_L_100_0 = "touch_event_l_100_0";
        
        public const string TOUCH_EVENT_L_100_2 = "touch_event_l_100_2";
        
        public const string TOUCH_EVENT_L_100_4 = "touch_event_l_100_4";
        
        public const string TOUCH_EVENT_L_100_5 = "touch_event_l_100_5";
        
        public const string TOUCH_EVENT_L_100_3 = "touch_event_l_100_3";
        
        public const string TOUCH_EVENT_L_100_1 = "touch_event_l_100_1";
    }
}
